language: php

php:
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: phpunit --configuration phpunit.travis.xml ./tests/com/mohiva/test/elixir

notifications:
  email:
    - travis.mohiva.elixir@mohiva.com
